# Build the entire project
[group('Build')]
build:
    mvn compile

# Run all the tests when no modules provided or a specific module tests
[group('Code Quality')]
test module='':
    mvn test {{ if module != "" { "-pl " + module } else { "" } }}

# Required fmt-maven-plugin to work correctly
# Format all code in the project
[group('Code Quality')]
fmt:
    mvn fmt:format

# Required maven-checkstyle-plugin to work correctly
# Run checkstyle to check for common mistakes and improve code quality
[group('Code Quality')]
lint:
    mvn checkstyle:check

# Run the project Spring Boot Application
[group('Run')]
run:
    mvn spring-boot:run

# Clean the project by removing generated target directory
[group('Clean')]
clean:
    mvn clean
