# Build the entire project
[group('Build')]
build:
    ./gradlew build

# Run all the tests when no modules provided or a specific module tests
[group('Code Quality')]
test module='':
    {{ if module != "" { "./gradlew " + module + ":test" } else { "./gradlew test" } }}

# Required Spotless plugin to work correctly
# Format all code in the project
[group('Code Quality')]
fmt:
    ./gradlew spotlessApply

# Required Checkstyle plugin to work correctly
# Run checkstyle to check for common mistakes and improve code quality
[group('Code Quality')]
lint:
    ./gradlew checkstyleMain checkstyleTest

# Run the project
[group('Run')]
run:
    ./gradlew bootRun

# Clean the project by removing generated target directory
[group('Clean')]
clean:
    ./gradlew clean
