# Build the entire project
[group('Build')]
build:
    go build ./...

# Run all the tests when no packages provided or a specific package tests
[group('Code Quality')]
test package='./...':
    go test {{ package }}

# Format all code in the project
[group('Code Quality')]
fmt:
    gofmt -w .

# Run go vet to check for common mistakes and improve code quality
[group('Code Quality')]
lint:
    go vet ./...

# Run the project
[group('Run')]
run:
    go run .

# Clean the project by removing generated build cache
[group('Clean')]
clean:
    go clean ./...
